/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PanelRouteImport } from './routes/panel/route'
import { Route as IndexImport } from './routes/index'
import { Route as PanelProductsImport } from './routes/panel/products'

// Create/Update Routes

const PanelRouteRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PanelProductsRoute = PanelProductsImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => PanelRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRoute
    }
    '/panel/products': {
      id: '/panel/products'
      path: '/products'
      fullPath: '/panel/products'
      preLoaderRoute: typeof PanelProductsImport
      parentRoute: typeof PanelRouteImport
    }
  }
}

// Create and export the route tree

interface PanelRouteRouteChildren {
  PanelProductsRoute: typeof PanelProductsRoute
}

const PanelRouteRouteChildren: PanelRouteRouteChildren = {
  PanelProductsRoute: PanelProductsRoute,
}

const PanelRouteRouteWithChildren = PanelRouteRoute._addFileChildren(
  PanelRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/panel': typeof PanelRouteRouteWithChildren
  '/panel/products': typeof PanelProductsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/panel': typeof PanelRouteRouteWithChildren
  '/panel/products': typeof PanelProductsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/panel': typeof PanelRouteRouteWithChildren
  '/panel/products': typeof PanelProductsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/panel' | '/panel/products'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/panel' | '/panel/products'
  id: '__root__' | '/' | '/panel' | '/panel/products'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PanelRouteRoute: typeof PanelRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PanelRouteRoute: PanelRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/panel"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/panel": {
      "filePath": "panel/route.tsx",
      "children": [
        "/panel/products"
      ]
    },
    "/panel/products": {
      "filePath": "panel/products.tsx",
      "parent": "/panel"
    }
  }
}
ROUTE_MANIFEST_END */
